version: "3"
services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    networks:
      - app-network

  greeting-service:
    build: ./greeting-service
    ports:
      - "8082:8082"
    depends_on:
      - user-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
